### ISSUE TITLE
Badly handled strings

### ISSUE THREAD

**Issue by admo** [S7NetPlus/s7netplus#180] opened 2018-08-22 08:23 UTC
Hi,
I work on application which communicates with S7-1200 and I've found that strings are handled wrongly by s7netplus library.
I've started with simple case in which I want to write string to the PLC:
```cs
string someString = "1234567890";
plc.Write(dataType, dbNumber, startByte, someString);
```
String in PLC has 10 characters. So, `someString` should fit to the PLC. But it does not. After executing above code, PLC reports error, and DB viewer shows rubbish. However, when I read back the data:
```cs
someString = (string)plc.Read(dataType, dbNumber, startByte, varType, 10);
```
I get correct string.

I've realized that when I define string with 10 characters, then it takes 13 bytes in the PLC. So, I decided to set string value to `1234567890` directly on the PLC. Application's read it, but the value of the string was `__12345678` (two underscores at the beginning means some non-printable characters).
The value of the two first characters was 10. When I set string value to `1` (one characters), then the first byte was equal to 10 and second was equal to 1. I've also checked the 13th byte, which has value 0 (null-character).

I came to the conclusion that the string layout in PLC memory looks as following:
`|r|n|1st char|2nd char|...|nth char|0|`
where `r` means how many bytes are reserved for the string, `n` how many characters actual string contains.

The correct string writing with actual support could looks like this:
```cs
string someString = "1234567890";
// Prepend someString with reserved bytes for string in the PLC and string length
plc.Write(dataType, dbNumber, startByte, (char)10 + ((char)someString.Length + someString));
```

Do you think that it could be corrected in your library?

**Comment by mycroes** [comment] 2018-08-22 08:36
Hi @admo,

If you create a `DataItem` which matches the string variable you should be able to write that using one of the `Write` overloads. The problem is that the data in the PLC consists of the following:
1. **[1 byte]** Reserved length for string
2. **[1 byte]** Length of current string
3. **[n bytes]** String content

Logically we could write the current length and the content only, but if we don't know the total length we would overwrite adjacent registers. If you use a `DataItem` you can define the length and it will take that into consideration (and cut off strings that are too long).

> I've realized that when I define string with 10 characters, then it takes 13 bytes in the PLC.
Not sure how you realized that, or how you defined that. I'm not a PLC programmer, but when I declare a string variable in a datablock in TIA Portal I have to specify the size [of the value it can hold] and it will add 2 bytes for the header. That means a string of maximum length 10 will occupy 12 bytes, not 13. I'm guessing the first byte in your header contains `11` and not `10`, but you can easily check that by reading that byte [with S7NetPlus].

Let me know if your issue is solved with the above suggestion and explanation.

**Comment by admo** [comment] 2018-08-22 10:59
Hi @mycroes,
I'll try. However, could you give me an example? I'm not able to figure out how to use `DataItem`s.

Last but not least. In my opinion the source code is the best documentation, and this library is developed like well-written book:). The only problem is that the interface promises correct strings handling:).
Could you consider changing it?

**Comment by mycroes** [comment] 2018-08-22 19:07
Hi @admo,

> I'll try. However, could you give me an example? I'm not able to figure out how to use `DataItem`s.

You can construct a `DataItem` like this:
```csharp
var di = new DataItem
{
    DataType = DataType.DataBlock,
    DB = 100,
    StartByteAdr = 22,
    Count = 10,
    VarType = VarType.StringEx,
    Value = "Hello World" // Yes, this more than 10 characters, it should be cut off automagically
};
```
This will represents a string _with header_ at **DB100,22** with length 10 (so it will read/write 2 additional bytes for the header).

You can use `Write(params DataItem[] dataItems)` to write the value:
```csharp
var di = ...; // See above
plc.Write(di);

var items = new List<DataItem> {di};
plc.Read(items); // Sorry, this expects a List<DataItem> and not params DataItem[] like the Write method does
Console.WriteLine(di.Value);
Console.WriteLine(di.Value.GetType());
```
I might add an overload which supports `params DataItem[] dataItems` for `Read` (in other words, flexible number of arguments) to ease `DataItem` usage.

> The only problem is that the interface promises correct strings handling:).
Could you consider changing it?

I took another look and the code and I was mistaken about needing to use `DataItem`. You gave the following sample:
```csharp
someString = (string)plc.Read(dataType, dbNumber, startByte, varType, 10);
```
Did you use `VarType.StringEx` as `varType`? It should actually work like that, verified that it should read `length + 2` bytes and correctly parse the result. Only for writing there's no overload which accepts `VarType`, so it can't figure what to write...

> Last but not least. In my opinion the source code is the best documentation, and this library is developed like well-written book:).

Not to rain on your parade, but with _the source code is the documentation_ people mean the actual source code. The documentation you see in Visual Studio is actual documentation, even though it's part of the same files as the code. Honestly the codebase is not in very good shape either, the API is too big and convoluted, but we're working on that (behind the scenes).

**Comment by mycroes** [comment] 2019-05-27 18:24
Closing, I guess the issue has been properly adressed, but feel free to reopen if you have more questions [on this specific topic].

**Closed by mycroes** 2019-05-27 18:24 UTC
