### ISSUE TITLE
Strings writing. Is it possible with this library?

### ISSUE THREAD

**Issue by Mallowan** [S7NetPlus/s7netplus#239] opened 2019-10-30 14:09 UTC
Hello guys, 
it's not clear from docs, whether it's possible to transfer a string to a certain DB's address (data type string) or not.
Perhaps docs are obsolete or so.
Could anyone share with this syntax?
Thanks in advance!

**Comment by adamsjdavid** [comment] 2019-11-20 05:40
It should be fairly trivial to implement this in your application. Simatic Strings follow a predictable format. On the PLC, they are simply a Byte Array with a default size of 256....that's 2 bytes for bookkeeping, 254 bytes for data. The structure is as follows:

First Byte: Max Size (Default 254)
Second Byte: Current String Size
Third Byte through Last Byte: String

Here's a code snippet that will take a string (value) and write it to a DB.

`public void WriteString(DataType dataType, int db, int startByteAdr, string value, byte maxSize=254)
        { 
            if (value.Length > maxSize)
                throw new ArgumentOutOfRangeException("You attempted to write a string larger than the maximum size!");
            List<byte> bytes = new List<byte>();
            bytes.Add((byte)maxSize);
            bytes.Add((byte)value.Length);
            foreach (char c in value) bytes.Add((byte)c);

            //Assuming you have a Plc object named plc...
            plc.WriteBytes(dataType, db, startByteAdr, bytes.ToArray());
        }`

I've put in a pull request containing a ReadString and WriteString method in the Plc class, but it may just be better to wrap that functionality up at the application level - convert a string to a byte array of the above pattern, then send it using the already existing WriteBytes function.

**Comment by FalcoGoodbody** [comment] 2019-12-12 06:10
Hello @Mallowan ,

I actually tried to write a string into a S7-1500 PLC and is works.
You can use the method "WriteBytes" and you need to convert the string into a bytearray.

`
byte[] bytearray = System.Text.Encoding.ASCII.GetBytes(AuftragsnummerKonti2);
            try
            {
                if (plcKonti2.IsConnected)
                {
                    plcKonti2.WriteBytes(DataType.DataBlock, 156, 0, bytearray);
                }
            }
            catch (Exception)
            {

                throw;
            }
`

For the S7-String-format it is neccessary to write into the first byte the maximum length of the string and ino the second byte the acutal length of the string.
This part is missing at my code. I need to implement it.

**Comment by FalcoGoodbody** [comment] 2019-12-12 08:26
Here is my full code wich is acutally tested. The String is written correctly to the PLC

```C#
// Auftragsnummer in byte-Array wandeln
            // für S7-String-Format:
            // 1. Byte = maximale Länge des Strings
            // 2. Byte = aktuelle Länge des Strings
            int aktuelleLaenge = AuftragsnummerKonti2.Length;
            int maxLaenge = 50;
            byte[] stringAuftrag = System.Text.Encoding.Default.GetBytes(AuftragsnummerKonti2);            
            byte[] bytearray = new byte[aktuelleLaenge + 2];
                       
            bytearray[0] = Convert.ToByte(maxLaenge);
            bytearray[1] = Convert.ToByte(aktuelleLaenge);

            // Array umkopieren für S7-String-Format
            for (int i = 2; i < bytearray.Length; i++)
            {
                bytearray[i] = stringAuftrag[i - 2];
            }

            // Auftragsnummer in Konti2 schreiben
            try
            {
                if (plcKonti2.IsConnected)
                {
                    plcKonti2.WriteBytes(DataType.DataBlock, 156, 0, bytearray);
                }
            }
            catch (Exception)
            {

                throw;
            }
```

**Comment by Mallowan** [comment] 2019-12-12 10:37
Finally someone answered! I already thought nobody writes strings to plc.  :)
Thank you! I will test your code.
I would discuss with about other stuff related to library. 

Mallowan

**Comment by FalcoGoodbody** [comment] 2019-12-12 12:46
Well for me it´s the first time since I work with S7.Net+ that I needed to write a string to the PLC.
But it´s only one year since I started working with S7.Net+.

**Comment by Mallowan** [comment] 2019-12-12 12:53
e-mail?

**Comment by FalcoGoodbody** [comment] 2019-12-12 12:54
Grimsey@outlook.de

**Comment by Mallowan** [comment] 2019-12-12 12:58
now, delete that, I've made a copy. Thanks.

**Comment by mycroes** [comment] 2020-09-08 20:19
Hi @Mallowan, I'm closing this issue because the problem is solved. If you run into additional problems, feel free to keep commenting here (and I will of course re-open if required).

**Closed by mycroes** 2020-09-08 20:19 UTC
